apiVersion: v1
kind: ConfigMap
metadata:
  name: logback-config
data:
  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="30 seconds">
        <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
            <withJansi>true</withJansi>
            <encoder>
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %5level ${PID:- } [%thread] %logger{30}.%M[%line] - %msg%n</pattern>
            </encoder>
        </appender>

        <root level="INFO">
            <appender-ref ref="CONSOLE" />
        </root>
        <logger name="org.springframework.data.mongodb.core" level="DEBUG"/>
    </configuration>
